[project]
name = "hoop-ranker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.9.2",
    "nba-api>=1.5.2",
    "polars>=1.9.0",
    "seaborn>=0.13.2",
]
